### ISSUE TITLE
Error: Cannot find module 'module "@deno/kv-darwin-x64"'

### ISSUE THREAD

**Issue by xcaeser** [denoland/denokv#45]
Working in Bun and NextJS 14.0.3, got this error using server actions
ran bun install @deno/kv
```tsx
<form action={write}>
        <Button type="submit">Click</Button>
 </form>
```
```ts
"use server";

import { openKv } from "@deno/kv";

export const write = async (formD: FormData) => {
  const kv = await openKv("kv.db");
  const result = await kv.set(["Greetings"], "hello!");
  console.log({ result });
  kv.close();
  return result;
};

```

<img width="725" alt="image" src="https://github.com/denoland/denokv/assets/8210099/f0059020-839c-485c-8d59-770fdb97214d">

Ran also bun i @deno/kv-darwin-x64 but I am still getting the same error.

**Comment by johnspurlock-skymethod** [comment]
_(Assuming you're on an intel mac from the package name)_

Take a look at your `node_modules`, you should see the root `kv` package under `@deno`, and then your arch-specific subfolder [`kv-darwin-x64`](https://www.npmjs.com/package/@deno/kv-darwin-x64)

Here's what bun does for me (I'm on an arm mac `kv-darwin-arm64`, but the idea is similar) on a quick test of a fresh install

<img width="531" alt="image" src="https://github.com/denoland/denokv/assets/47259736/84123962-0d2f-41fa-b66e-56689ae8aa7f">

**Comment by xcaeser** [comment]
I confirm that it's there on a fresh install again, but not working still

Could you please guide me, if possible?

<img width="339" alt="image" src="https://github.com/denoland/denokv/assets/8210099/9dcf7a5a-6be9-4384-b510-6512864f7fa8">

**Comment by johnspurlock-skymethod** [comment]
Hmm, maybe try it in a simple bun cli script first, in case it's something in the Next setup.

**Comment by xcaeser** [comment]
Tried both a simple index.ts bun script and also a hono server.
This is what I get now

```
Started server http://localhost:3007
55 |                 throw new Error(`Unexpected 'decodeV8': ${decodeV8}`);
56 |             }
57 |             return { encodeV8: encodeV8, decodeV8: decodeV8 };
58 |         }
59 |         if ("Bun" in dntShim.dntGlobalThis) {
60 |             throw new Error(`Bun provides v8.serialize/deserialize, but it uses an incompatible format (JavaScriptCore). Provide explicit 'encodeV8' and 'decodeV8' functions via options.`); // https://discord.com/channels/876711213126520882/888937948345684008/1150135641137487892
                       ^
error: Bun provides v8.serialize/deserialize, but it uses an incompatible format (JavaScriptCore). Provide explicit 'encodeV8' and 'decodeV8' functions via options.
```

**Comment by johnspurlock-skymethod** [comment]
Ok, that's better, you're loading the package.  That isolates your initial loading problem to something in Next magic.

The new error you are seeing is an intentional warning that's thrown by @deno/kv, as Bun's `v8` module serialize/deserialize functions are implemented, but use JavaScriptCore serialization under the hood, which are not compatible with actual V8.

This can present data corruption problems if you want to use DBs on Deno Deploy or other DBs shared with Node/Deno-created dbs that use actual V8 serialization, you might create data you cannot read, or vice versa.

If you are only going to ever write to your DBs in Bun, you can force the use of Bun's serializers by providing a custom `encodeV8`, `decodeV8` explicitly as the second parameter to `openKv`.  Note any data will be unreadable by Node (using @deno/kv, or Deno), since they use the actual V8 format.

e.g. something like:
```ts
import { Hono } from "hono";
import { openKv } from "@deno/kv";
import { serialize as encodeV8, deserialize as decodeV8 } from "v8"; // actually JavaScriptCore format on Bun!

const app = new Hono();

app.get("/", async (c) => {
  const kv = await openKv("kv.db", { encodeV8, decodeV8 });
  const result = await kv.set(["Greetings"], "hello!");
  console.log({ result });
  kv.close();
  return c.json(result);
});

export default {
  port: 3007,
  fetch: app.fetch,
};
```

I know the Bun team is working hard on full Node built-in module support, and hope they can do true V8-format serialization at some point in the future.
